# --- Configuração do Servidor ---
# Define a porta em que a aplicação vai rodar
server.port=8080

# --- Configuração do Banco de Dados (MariaDB Local) ---
# URL de conexão com o seu banco de dados local
spring.datasource.url=jdbc:mariadb://localhost:3306/SistemaAgendamento
spring.datasource.username=UserAgendamento
spring.datasource.password=12345

# --- Configuração do Hibernate/JPA ---
# 'update': atualiza o schema do banco se houver mudanças nas entidades
spring.jpa.hibernate.ddl-auto=update
# Mostra no console o SQL que o Hibernate está executando
spring.jpa.show-sql=true
# Formata o SQL exibido no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true

# --- Configuração do Swagger/Springdoc ---
# Define o caminho para a interface do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html